name: Node.js Package

on:
    release:
        types: [created]

permissions:
    contents: read

jobs:
    npm-release:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
              with:
                  fetch-depth: 0
            - uses: actions/setup-node@v4
              with:
                  node-version: "18.x"
                  registry-url: "https://registry.npmjs.org"
                  scope: "@nayotta"
            - run: |-
                  TAG_VERSION="${GITHUB_REF_NAME#v}"
                  cat package.json | jq --arg arg1 "${TAG_VERSION}" '.version |= $arg1' > package.json.tmp && mv package.json.tmp package.json
                  echo './package.json'
                  cat package.json | grep version
            - run: npm install
            - run: npm run lint
            - run: npm run build
            - run: npm publish --access public
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_ACCESS_TOKEN }}

    pkg-release:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
              with:
                  fetch-depth: 0
            - uses: actions/setup-node@v4
              with:
                  node-version: "18.x"
                  registry-url: "https://npm.pkg.github.com"
                  scope: "@nayotta"
            - run: |-
                  TAG_VERSION="${GITHUB_REF_NAME#v}"
                  cat package.json | jq --arg arg1 "${TAG_VERSION}" '.version |= $arg1' > package.json.tmp && mv package.json.tmp package.json
                  echo './package.json'
                  cat package.json | grep version
            - run: npm install
            - run: npm run lint
            - run: npm run build
            - run: npm publish
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.PKG_ACCESS_TOKEN }}
